name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,6 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 签到
      run: |
        pip install -r requirements.txt
        
        COOKIE='${{ secrets.COOKIE }}'
        CSRFTOKEN='${{ secrets.CSRFTOKEN }}'
        python3 checkin.py <<EOF
        ${COOKIE}
        ${CSRFTOKEN}
        EOF
        JUEJINCOOKIE='${{ secrets.JUEJINCOOKIE }}'
        ./juejin.sh JUEJINCOOKIE
        echo "掘金签到成功"
